DominicanaLimpia/Controllers/ReporteController.cs
using DominicanaLimpia.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DominicanaLimpia.Controllers
{

    [SessionExpire]
    public class ReporteController : Controller
    {

        private DominicanalimpiaEntities2 db = new DominicanalimpiaEntities2();

        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public JsonResult obtenertotal() {
          
            
            var total =  Session["TotalUnificado"].ToString();
            total = string.Format("{0:#,0.00}", Convert.ToDouble(total));


            return Json(total, JsonRequestBehavior.AllowGet);
        

        }

        public JsonResult BuscarReporte(int TipoReporte, string Desdef, string Hastaf , bool VerTodos = false)
        {


            DateTime Desde = Convert.ToDateTime(Desdef);
            DateTime Hasta = Convert.ToDateTime(Hastaf);

            int[] ProvinciasSum = new int[23];

            //Consulta General
            var requests = db.Objetivo1.Where(x => x.Desde >= Desde && x.Desde <= Hasta).ToList();
            //formularioM para que sea generico en todos 
            var FormularioM = db.FormularioM.Where(x => x.Desde >= Desde && x.Desde <= Hasta).ToList();


            //para los roles id 5
            if (VerTodos == false)
            {
                if (Session["RodId"].ToString() == "2" || Session["RodId"].ToString() == "5")
                {
                    var munn = Session["MunicipiosAsignados"].ToString().Split(',');


                    int[] marks = new int[10];


                   // string responsables = "";
                    for (int i = 0; i < munn.Length; i++)
                    {
                        if (munn[i] != "0")
                        {
                            marks[i] =  Convert.ToInt32(munn[i]);
                            //responsables = responsables + "," + munn[i];
                        }
                    }
                   
                    FormularioM = FormularioM.Where(r => marks.ToList().Contains( Convert.ToInt32(r.ProvinciaId))).ToList();
                    requests = requests.Where(r => marks.ToList().Contains( Convert.ToInt32(r.MunicipioId))).ToList();
                }
            }


            if (TipoReporte == 1)
            {


                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p2);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p3);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p4);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p5);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p6);
                    ProvinciasSum[i] =  Convert.ToInt32( ProvinciasSum[i] + ((int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p7) * 3.3));
                  //  ProvinciasSum[i] =  (int)(ProvinciasSum[i] * 3.3);
                    
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p8);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p9);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p10);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p12);

                    //con el maestro de formulario ahora
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P18);
                   // ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P19);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P22);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P23);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P29);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P32);

                }
            }


            //Metas de hogares sumatoria de la pretunta 8
            if (TipoReporte == 2)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p7);
                }
            }

            //metas de comercios
            if (TipoReporte == 3)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P15);
                }
            }

            //METAS DE ESCUELAS
            if (TipoReporte == 4)
            {
                requests = requests.GroupBy(i => i.EscuelaId).Select(group => group.First()).ToList();

                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p1);
                }
            }

            //METAS DE ESCUELAS
            if (TipoReporte == 5)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p4);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p5);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p6);
                }
            }

            //METAS DE ESCUELAS
            if (TipoReporte == 6)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                   // ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p2);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p3);
                }
            }


            //METAS DE ESCUELAS
            if (TipoReporte == 7)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p2);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p3);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p4);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p5);
                    ProvinciasSum[i] = ProvinciasSum[i] + (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p6);
                }
            }


            //metas de comercios
            if (TipoReporte == 8)
            {
                for (int i = 1; i < ProvinciasSum.Length; i++)
                {
                    //ProvinciasSum[i] = ProvinciasSum[i] + (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P14);
                    ProvinciasSum[i] = (int)FormularioM.Where(x => x.ProvinciaId == i).Sum(z => z.P16);
                }
            }

            //Metas docentes sumatoria de la pretunta p1
            if (TipoReporte == 9)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p2);
                }
            }


            if (TipoReporte == 10)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p4);
                }
            }

            if (TipoReporte == 11)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p5);
                }
            }



            if (TipoReporte == 12)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p6);
                }
            }

            if (TipoReporte == 13)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p8);
                }
            }

            if (TipoReporte == 14)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p9);
                }
            }

            if (TipoReporte == 15)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.p10);
                }
            }

            if (TipoReporte == 16)
            {
                for (int i = 0; i < ProvinciasSum.Length; i++)
                {
                    ProvinciasSum[i] = (int)requests.Where(x => x.MunicipioId == i).Sum(z => z.P112);    
                }
            }

DominicanaLimpia/Views/Reportes/ReportePorActividad.cshtml
@{
    ViewBag.Title = "Reporte Por Actividad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@*@{
    ViewBag.Title = "Reportes por actividad";
    Layout = "~/Views/Shared/_Layout.cshtml";

}*@

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css" />
<script src="~/Content/Datepicket.js"></script>

<br />
<br />
<div class="col-md-14 mb-4">
    <div class="card">
        <div class="card-body">
            <br /><br />
                  <h4>Reportes por actividad</h4>
            <hr />

            <div class="well">
                <table class="table">
                    <thead>
                        <tr>
                            <th><strong>Tipo de reporte:</strong>  @Html.DropDownList("TipoReporteId", (IEnumerable<SelectListItem>)ViewBag.TipoReporte, null, new { @class = "form-control" })   </th>
                            <th> <strong>Desde:</strong> <input type="text" class="form-control" name="DesdeFecha" id="DesdeFechaR"></th>
                            <th> <strong>Hasta:</strong> <input type="text" class="form-control" name="HastaFecha" id="HastaFechaR"></th>
                            <th><button type="button" class="btn btn-success" onclick="Imprimir()">Descargar</button></th>

                        </tr>

                    </thead>
                </table>
            </div>
            <br /><br />


        </div>
    </div>
</div>

<script type="text/javascript">

        $("#DesdeFechaR").datepicker({
        autoclose: true,
        todayHighlight: true,
           format: 'd M, yyyy'
    }).datepicker('update', new Date());

    $("#HastaFechaR").datepicker({
        autoclose: true,
        todayHighlight: true,
         format: 'd M, yyyy'


    }).datepicker('update', new Date());


        function Imprimir() {

        var TipoR = $('#TipoReporteId :selected').val();
        var desde = $("#DesdeFechaR").val();
        var hasta = $("#HastaFechaR").val();
        var _url = '@Url.Action("ImprimirReporteActividad", "Reporte")';

       window.location = '/Reporte/ImprimirReporteActividad?TipoReporte=' + TipoR + "&Desdef="+ desde+ "&Hastaf="+ hasta; 

    }


</script>

DominicanaLimpia/Views/Reportes/Reportes.cshtml
@{
    ViewBag.Title = "Reportes";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css" />
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>*@
<script src="~/Content/Datepicket.js"></script>

<br />
<br />
<div class="col-md-14 mb-4">
    <div class="card">
        <div class="card-body">
            <br /><br />
            <h4>Reportes</h4>
            <hr />

            <div class="well">
                <table class="table">
                    <thead>
                        <tr>
                            <th><strong>Tipo de reporte:</strong>  @Html.DropDownList("TipoReporteId", (IEnumerable<SelectListItem>)ViewBag.TipoReporte, null, new { @class = "form-control" })   </th>
                            <th> <strong>Desde:</strong> <input type="text" class="form-control" name="DesdeFecha" id="DesdeFechaR"></th>
                            <th> <strong>Hasta:</strong> <input type="text" class="form-control" name="HastaFecha" id="HastaFechaR"></th>

                            @if (Session["RodId"].ToString() == "5") { 
                                <th><strong>Mostrar todos</strong> <input class="form-control" type="checkbox" value="" id="defaultCheck1"></th>
                            }
                            <th><button type="button" class="btn btn-success" onclick="Aparece()">Buscar</button></th>
                        </tr>
                    </thead>
                </table>
            </div>

            <br /><br />

            <div class="col-md-9 mb-4" >
                <!--Card-->
                <div class="card" style="width: 1430px;">
                    <!--Card content-->
                    <div class="card-body hidden" id="chartContainer">
                        <canvas id="myChart"></canvas>
                    </div>
                    
                </div>
                <!--/.Card-->
            </div>
        </div></div></div>


<script type="text/javascript">

        $("#DesdeFechaR").datepicker({
        autoclose: true,
        todayHighlight: true,
        format: 'd M, yyyy'
    }).datepicker('update', new Date());

    $("#HastaFechaR").datepicker({
        autoclose: true,
        todayHighlight: true,
          format: 'd M, yyyy'


    }).datepicker('update', new Date());



    function Aparece() {


        var TipoR = $('#TipoReporteId :selected').val();
        var desde = $("#DesdeFechaR").val();
        var hasta = $("#HastaFechaR").val();
        var vertodos = false;

        var checkBox = document.getElementById("defaultCheck1");

        if (checkBox != null) {
            if (checkBox.checked == true) {
                vertodos = true;
            } else {
                vertodos = false;
            }
    }
        var _url = '@Url.Action("BuscarReporte", "Reporte")';

            $.ajax({
                    type: 'POST',
                    url: _url,
                data: JSON.stringify({ TipoReporte: TipoR, Desdef: desde, Hastaf: hasta, VerTodos: vertodos}),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                success: function (data) {
                     
                       
$.ajax({
    type: "GET",
    url: '@Url.Action("obtenertotal", "Reporte")',
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    success: function (total) {

                       document.getElementById("chartContainer").innerHTML = '&nbsp;';
                       document.getElementById("chartContainer").innerHTML = ' <button type="button" onclick="Imprimir()" class="btn btn-warning">Imprimir</button><p>Total Unificado : '+total+'</p><canvas id="myChart"></canvas>';


                        var ctx = document.getElementById("myChart").getContext('2d');

                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: ["Azua", "Cotuí", "Jarabacoa", "Puerto Plata", "Sabana de la Mar", "Salcedo", "San Juan de la Maguana", "Villa Jaragua", "Villa Tapia",
                                    "Verón Punta Cana (D.M.)",
                                    "Baní",
                                    "Dajabón ",
                                    "Esperanza ",
                                    "Hato Mayor",
                                    "Mao",
                                    "Moca ",
                                    "San José de Ocoa",
                                    "San Pedro de Macorís",
                                    "Bánica",
                                    "Constanza",
                                    "Los Botados (D.M.)",
                                    "San Francisco de Macorís",],

                                datasets: [{
                                    label: '# Cantidad',
 data: [data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10], data[11], data[12], data[13], data[14], data[15], data[16], data[17], data[18], data[19], data[20], data[21], data[22]],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 206, 86, 0.2)',
                                        'rgba(75, 192, 192, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 159, 64, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(54, 162, 235, 0.2)',
                                        'rgba(255, 99, 132, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(153, 102, 255, 0.2)',
                                        'rgba(255, 99, 132, 0.2)',

                                    ],
                                    borderColor: [
                                        'rgba(255,99,132,1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 3
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: false
                                        }
                                    }]
                                }
                            }
                        });




                                    },
    error: function() { alert('A error'); }
});

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alertify.warning('Error al soliictar la peticion! ');
                }


                });

        $(".card-body").removeClass("hidden");
    }


    function Imprimir() {

        var TipoR = $('#TipoReporteId :selected').val();
        var desde = $("#DesdeFechaR").val();
        var hasta = $("#HastaFechaR").val();
        var _url = '@Url.Action("ImprimirReporte", "Reporte")';


       window.location = '/Reporte/ImprimirReporte?TipoReporte=' + TipoR + "&Desdef="+ desde+ "&Hastaf="+ hasta; 

               //$.ajax({
               //     type: 'POST',
               //     url: _url,
               //     data: JSON.stringify({ TipoReporte: TipoR , Desde: desde, Hasta : hasta }),
               //     contentType: "application/json; charset=utf-8",
               //     dataType: "json",
               //    success: function (Data) {

               //        alert(Data);

               //  //var bytes = new Uint8Array(Rdata.FileContents); 
               //  //   var blob = new Blob([bytes], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
               //  //   var link = document.createElement('a');
               //  //   link.href = window.URL.createObjectURL(blob);
               //  //   link.download = "myFileName.xlsx";
               //  //   link.click();




               //         //console.log(data);
               //         //if (data.error == false) {
               //         //    window.location.href = '/Formulario/Exito/';
               //         //} else {
               //         //    alertify.warning('Error al insertar los valores, contacte a su corrdinador ! ');
               //         //    return;
               //         //}
               //     },
               //     error: function (jqXHR, textStatus, errorThrown) {
               //         alertify.warning('Error al soliictar la peticion de guardado! ');
               //     }
               // });


    }




</script>