DominicanaLimpia/Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DominicanaLimpia;
using DominicanaLimpia.Models;
using DominicanaLimpia.ModelViews;
using DominicanaLimpia.Utilidades;
using RotativaHQ.MVC5;

namespace DominicanaLimpia.Controllers
{
    [SessionExpire]
    public class FormularioController : Controller
    {
        private DominicanalimpiaEntities2 db = new DominicanalimpiaEntities2();

        // GET: Formulario
        public ActionResult Index()
        {

            string responsables = "";
            var distinctClientsPerEvent = db.FormularioM.GroupBy(m => m.Desde)
                                                              .Select(x => x.FirstOrDefault());

            distinctClientsPerEvent = db.FormularioM.Where(x => x.FormularioId != 0);

            //si es Responsable de territorio
            if (Session["RodId"].ToString() == "5")
            {
                int idusuario = Convert.ToInt32(Session["UsuarioId"].ToString());
                var MisCoordinadores = db.Usuarios.Where(x => x.ResponsableId == idusuario).ToList();
                foreach (var item in MisCoordinadores)
                {
                    responsables = responsables + "," + item.UsuarioId;
                }

                distinctClientsPerEvent = db.FormularioM.Where(r => responsables.Contains(r.UsuarioId.ToString()));
            }

            //si es coordinador
            if (Session["RodId"].ToString() == "2")
            {
                int idusuario = Convert.ToInt32(Session["UsuarioId"].ToString());

                distinctClientsPerEvent = db.FormularioM.Where(x => x.UsuarioId == idusuario);
            }


            // var   Modelo = distinctClientsPerEvent.Where(x=>x)
            return View(distinctClientsPerEvent);
        }

        // GET: Formulario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.Formulario.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // GET: Formulario/Create
        public ActionResult Create()
        {

            Formulario formulario = new Formulario();
      

            int idusuario = Convert.ToInt32(Session["UsuarioId"].ToString());
            var usuario = db.Usuarios.Where(x => x.UsuarioId ==  idusuario).ToList().FirstOrDefault();
            var myInClause =  usuario.MunicipiosId.Split(',');
            var results = db.Municipios.Where(r => myInClause.Contains(r.MunicipioId.ToString()));
            ViewBag.Municipios = new SelectList(results, "MunicipioId", "Provincia_Nombre");


            var _Escuelas = usuario.MunicipiosId.Split(',');
            var resultadoEsc = db.Escuelas.Where(r => _Escuelas.Contains(r.MunicipioId.ToString())).ToList();

            var escuelas = db.Escuelas.Where(x => x.EscuelaId == 202).FirstOrDefault();
            resultadoEsc.Add(escuelas);


            ViewBag.EscuelaGrid = new SelectList(resultadoEsc, "EscuelaId", "Descripcion");
            ViewBag.Pregunta16 = new SelectList(LlenarComboSiNo(), "Indice", "Value");
            ViewBag.Escuelas13 = new SelectList(db.Escuelas.Where(r=> _Escuelas.Contains(r.MunicipioId.ToString())).ToList(), "EscuelaId", "Descripcion");

            formulario.Preguntas = db.Preguntas.ToList();
            return View(formulario);
        }

        // POST: Formulario/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Formulario formulario)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    var idnumero = 0;
                    var numeroformulario = db.FormularioM.ToList().LastOrDefault();

                    if (numeroformulario == null)
                    {
                        idnumero = 1;
                    }
                    else
                    {
                        idnumero = Convert.ToInt32(numeroformulario.NumeroFormulario + 1);
                    }
                    
                    FormularioM nuevoform = new FormularioM();
                    nuevoform.Desde = Convert.ToDateTime(formulario.DesdeFecha);
                    nuevoform.Hasta = Convert.ToDateTime(formulario.HastaFecha);
                    nuevoform.UsuarioId = Convert.ToInt16(Session["UsuarioId"].ToString());
                    nuevoform.ProvinciaId = formulario.ProvinciaId;
                    nuevoform.Comentario = formulario.Comentario;
                    nuevoform.Estatus = "A";
                    nuevoform.NumeroFormulario = idnumero;
                    nuevoform.P13 = formulario.Valores[12];
                    nuevoform.P14 = formulario.Valores[13];
                    nuevoform.P15 = formulario.Valores[14];
                    nuevoform.P16 = formulario.Valores[15];
                    nuevoform.P17 = formulario.Valores[16];
                    nuevoform.P18 = formulario.Valores[17];
                    nuevoform.P19 = formulario.Valores[18];
                    nuevoform.P20 = formulario.Valores[19];
                    nuevoform.P21 = formulario.Valores[20];
                    nuevoform.P22 = formulario.Valores[21];
                    nuevoform.P23 = formulario.Valores[22];
                    nuevoform.P24 = formulario.Valores[23];
                    nuevoform.P25 = formulario.Valores[24];
                    nuevoform.P26 = formulario.Valores[25];
                    nuevoform.P27 = formulario.Valores[26];
                    nuevoform.P28 = formulario.Valores[27];
                    nuevoform.P29 = formulario.Valores[28];
                    nuevoform.P30 = formulario.Valores[29];
                    nuevoform.P31 = formulario.Valores[30];
                    nuevoform.P32 = formulario.Valores[31];

                    db.FormularioM.Add(nuevoform);
                    db.SaveChanges();

                    return View("~/Views/Formulario/Exito.cshtml");

                }catch(Exception ex)
                {
                    throw ex.InnerException;
                }
            }

            return View(formulario);
        }


        public List<Combo> LlenarComboSiNo()
        {
            List<Combo> Combo = new List<Combo>();

            Combo.Add(new Combo { Indice = 1, Value = "Si" });
            Combo.Add(new Combo { Indice = 2, Value = "No" });
            return Combo;
        }


        public JsonResult GuardarFormulario(Formulario formulario)
        {
            var error = false;

            try
            {


                //var testtt = Convert.ToDateTime(formulario.DesdeFecha);
               // var splitDesde = formulario.DesdeFecha.Split('/');
               // var splitHasta = formulario.HastaFecha.Split('/');

                formulario.DesdeFecha = Convert.ToDateTime(formulario.DesdeFecha).ToString();
                formulario.HastaFecha = Convert.ToDateTime(formulario.HastaFecha).ToString();

                FormularioM nuevoform = new FormularioM();
                nuevoform.Desde = Convert.ToDateTime(String.Format("{0:MM/dd/yyyy}", formulario.DesdeFecha));
                nuevoform.Hasta = Convert.ToDateTime(String.Format("{0:MM/dd/yyyy}", formulario.HastaFecha));
                nuevoform.UsuarioId = Convert.ToInt16(Session["UsuarioId"].ToString());
                nuevoform.ProvinciaId = formulario.ProvinciaId;
                nuevoform.Comentario = formulario.Comentario;
                nuevoform.Estatus = "I";
                nuevoform.NumeroFormulario = 1;
                nuevoform.P13 = formulario.Valores[12];
                nuevoform.P14 = formulario.Valores[13];
                nuevoform.P15 = formulario.Valores[14];
                if(formulario.Pregunta16 == 2)
                {
                    formulario.Pregunta16 = 0;
                }
                nuevoform.P16 = formulario.Pregunta16;

                nuevoform.P17 = formulario.Valores[15];
                nuevoform.P18 = formulario.Valores[16];
                nuevoform.P19 = formulario.Valores[17];
                nuevoform.P20 = formulario.Valores[18];
                nuevoform.P21 = formulario.Valores[19];
                nuevoform.P22 = formulario.Valores[20];
                nuevoform.P23 = formulario.Valores[21];
                nuevoform.P24 = formulario.Valores[22];
                nuevoform.P25 = formulario.Valores[23];
                nuevoform.P26 = formulario.Valores[24];
                nuevoform.P27 = formulario.Valores[25];
                nuevoform.P28 = formulario.Valores[26];
                nuevoform.P29 = formulario.Valores[27];
                nuevoform.P30 = formulario.Valores[28];
                nuevoform.P31 = formulario.Valores[29];
                nuevoform.P32 = formulario.Valores[30];
                db.FormularioM.Add(nuevoform);
                db.SaveChanges();
         
                var numeroformulario = db.FormularioM.ToList().LastOrDefault();

                Objetivo1 Objetivos = new Objetivo1();

                    foreach (var item in formulario.ObjetivoLista)
                    {
                        Objetivos.FormularioId = numeroformulario.FormularioId;
                        Objetivos.EscuelaId = item.IdEscuela;
                        Objetivos.UsuarioId = Convert.ToInt16(Session["UsuarioId"].ToString());
                        Objetivos.p1 = item.P1;
                        Objetivos.p2 = item.P2;

DominicanaLimpia/Views/Formulario/Delete.cshtml
@model DominicanaLimpia.Formulario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PreguntaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreguntaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hasta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idusuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idusuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DominicanaLimpia/Views/Formulario/Details.cshtml
@model DominicanaLimpia.Formulario

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PreguntaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreguntaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hasta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idusuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idusuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FormularioId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DominicanaLimpia/Views/Formulario/Edit.cshtml
@model DominicanaLimpia.Formulario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formulario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FormularioId)

        <div class="form-group">
            @Html.LabelFor(model => model.PreguntaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PreguntaId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PreguntaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desde, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hasta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hasta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hasta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idusuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idusuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idusuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DominicanaLimpia/Views/Formulario/Exito.cshtml
@{
    ViewBag.Title = "Exito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">*@
@*<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>*@
@*<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>*@

<div class="form-horizontal">
    <br /> <br />
    <div class="col-md-14 mb-4">
        <div class="card">
            <div class="container">
                <div class="row text-center">
                    <div class="col-sm-6 col-sm-offset-3" style="    margin-left: 23%;">
                        <br><br> <h2 style="color:#0fad00">Formulario guardado !</h2>
                        <img src="https://cdn3.iconfinder.com/data/icons/flat-actions-icons-9/792/Tick_Mark_Dark-128.png">
                        <h3>Señ@r, @Session["NombreUsuario"].ToString()</h3>
                        <p style="font-size:20px;color:#5C5C5C;">
                           Gracias por completar el formulario !
                        </p>
                        <br><br>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

DominicanaLimpia/Views/Formulario/Index.cshtml
@model IQueryable<DominicanaLimpia.FormularioM>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    DominicanalimpiaEntities2 db = new DominicanalimpiaEntities2();
}
<br />
<br />
<div >
    <div >
        <div >

            <h4> <strong>  Listado de formularios creados   </strong></h4>
            <hr />
            <p>
                @if (Session["RodId"].ToString() != "1" && Session["RodId"].ToString() != "4"  && Session["RodId"].ToString() != "5")
                {
            <div class="text-right">
                <input value="Crear formulario" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Formulario")'" />
            </div>
                }

            </p>
            <table class="table table-hover" id="dtBasicExample">
                <thead  class="blue lighten-4">
                    <tr>
                        <th>
                            Usuario
                        </th>
                        <th>
                            Territorio
                        </th>
                        <th>
                            Fecha desde
                        </th>
                        <th>
                            Fecha Hasta
                        </th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
        {
                    <tr>
                        <td>
                            @{
                                var Nombreusuario = db.Usuarios.Where(x => x.UsuarioId == item.UsuarioId).Select(x => x.Nombre_Completo).FirstOrDefault();
                            }
                            @Nombreusuario
                        </td>

                        <td>
                            @{
                                var Minucipio = db.Municipios.Where(x => x.MunicipioId == item.ProvinciaId).Select(x => x.Provincia_Nombre).FirstOrDefault();
                            }
                            @Minucipio
                        </td>

                        <td>
                            @{ 
                                var dateOnlyString = item.Desde.ToString();
                                dateOnlyString = dateOnlyString.Replace("12:00:00 AM", "");



                                var dateOnlyString1 = item.Hasta.ToString();
                                dateOnlyString1 = dateOnlyString1.Replace("12:00:00 AM", "");

                            }
                          @item.Desde.Value.Day  @item.Desde.Value.ToString("MMM") @item.Desde.Value.Year
                        </td>
                        <td>
                            @item.Hasta.Value.Day  @item.Hasta.Value.ToString("MMM") @item.Hasta.Value.Year
                        </td>
                        <td>


                            <button type="button" class="btn btn-primary btn-sm" title="Descargar" onclick="AbrirReporte(@item.FormularioId)" @*onclick="location.href='@Url.Action("VerFormulario", "Formulario", new { @id = item.FormularioId})'"*@><i class="far fa-eye"></i></button>



                            @if (item.Estatus.Trim() == "I")
                            {

                                if (Session["RodId"].ToString() != "4")
                                {
                                    <button type="button" class="btn btn-green btn-sm" title="Editar" onclick="location.href='@Url.Action("EditarFormularioM", "Formulario", new { id = item.FormularioId })'"><i class="far fa-edit"></i></button>
                                    <button type="button" class="btn btn-red btn-sm" title="Eliminar" onclick="location.href='@Url.Action("DeleteConfirmed", "Formulario", new { id = item.FormularioId })'"><i class="far fa-trash-alt"></i></button>
                                }
                            }

                            @if (Session["RodId"].ToString() == "5")
                            {

                                if (item.Estatus.Trim() == "I")
                                {
                                    <button type="button" title="Aprobar" class="btn btn-orange btn-sm" onclick="location.href='@Url.Action("ValidarFormulario", "Formulario", new { id = item.FormularioId })'"><i class="fas fa-edit"></i></button>
                                }
                            }


                        </td>
                    </tr>
}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    function AbrirReporte(id) {
         window.open('/Formulario/VerFormulario?id='+id+'', '_blank', 'left=100,top=100,width=1000,height=1000,toolbar=1,resizable=0');
    }

</script>

DominicanaLimpia/Views/Formulario/VistaFormulario.cshtml
@model DominicanaLimpia.ModelViews.FormularioModelView

@{
    int cobjetivo1 = 1;
    int cobjetivopart2 = 1;
    int contador = 1;
    DominicanalimpiaEntities2 db = new DominicanalimpiaEntities2();
}

<br />
<br />

<div class="well">
    <table class="table">
        <thead>
            <tr>
                @{
                    DateTime dateOnlyString = Convert.ToDateTime(ViewBag.FechaDesde);
                    var fecha1 = dateOnlyString.Date.ToShortDateString();

                    DateTime dateOnlyString1 = Convert.ToDateTime(ViewBag.FechaHasta);
                    var fecha2 = dateOnlyString1.Date.ToShortDateString();
                }
                <th><h5> <strong>Desde:</strong>   @dateOnlyString.Day  @dateOnlyString.ToString("MMM") @dateOnlyString.Year</h5></th>
                <th><h5><strong>Hasta:</strong>  @dateOnlyString1.Day  @dateOnlyString1.ToString("MMM") @dateOnlyString1.Year </h5></th>
            </tr>
            <br />
            <tr>
                <th> <h3> <strong>Responsable de territorio:</strong>  </h3> <h4> @Session["NombreResponsableReporte"].ToString()  -  @Session["NombreProvincia"].ToString()</h4></th>
            </tr>

        </thead>
    </table>
</div>
<br />
<br />

<br />
<br />
<h3><strong>Objetivo 1</strong></h3>
<br />

@foreach (var item in Model.Preguntas)
{

    <div class="form-group">

        @if (cobjetivo1 <= 12)
        {
            <div class="block" style="display: inline-block">
                <strong> @cobjetivo1 - @item.Descripcion</strong>
            </div>
        }

    </div>
    if (cobjetivo1 == 6)
    {
        break;
    }
    cobjetivo1 = cobjetivo1 + 1;

}
<br />

<table class="table table-hover" id="BasicExample">
    <thead class="blue lighten-4">
        <tr>
            <th>
                Escuela
            </th>
            <th>
                P1
            </th>
            <th>
                P2
            </th>
            <th>
                P3
            </th>
            <th>
                P4
            </th>
            <th>
                P5
            </th>
            <th>
                P6
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.objetivo1)
        {
            <tr>
                <td>

                    @db.Escuelas.Where(x => x.EscuelaId == item.EscuelaId).FirstOrDefault().Descripcion

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p5)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p6)
                </td>
            </tr>
        }
    </tbody>
</table>
<br />

@{cobjetivo1 = 1; }

@foreach (var item in Model.Preguntas)
{
    <div class="form-group">

        @if (cobjetivo1 >= 7 && cobjetivo1 <= 12)
        {
            <div class="block" style="display: inline-block">
                <strong> @cobjetivo1 - @item.Descripcion</strong>
            </div>
        }
    </div>
    cobjetivo1 = cobjetivo1 + 1;
}
<br />
<br />
<br />

<table class="table table-hover" id="BasicExample">
    <thead class="blue lighten-4">
        <tr>

            <th>
                P7
            </th>
            <th>
                P8
            </th>
            <th>
                P9
            </th>
            <th>
                P10
            </th>
            <th>
                P11.1
            </th>
            <th>
                P11.2
            </th>

            <th>
                P12
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.objetivo1)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.p7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p10)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.P111)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.P112)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.p12)
                </td>
            </tr>

        }
    </tbody>
</table>

<br />
<br />
<br />

<div class="form-group" style="position:relative; left:80px; top:2px; width:500px;">
    <strong>Comentario Objetivo  1</strong>
    <textarea class="form-control" rows="7">@Model.Comentarioobj1</textarea>
</div>

@foreach (var item in Model.Preguntas)
{

    <div class="form-group">

        @if (contador >= 13)
        {



            <div class="block" style="display: inline-block">

                @if (contador == 13)
                {
                    <h3><strong>Objetivo 2</strong></h3>
                    <br /><hr />
                }
                @if (contador == 16)
                {
                    <h3><strong>Objetivo 3</strong></h3>
                    <br /><hr />
                }
                @if (contador == 27)
                {
                    <h3><strong>Objetivo 4</strong></h3>
                    <br /><hr />
                }

                <strong> @contador - @item.Descripcion</strong>
                <p>
                    <input value="@Model.Valores[contador]" />
                </p>

                @if (contador == 18 || contador == 19 || contador == 20 || contador == 27 || contador == 28 || contador == 29
                    || contador == 30 || contador == 31 || contador == 32)
                {
                    <br />
                    <label for="validationDefault01">Dirección/Descripción</label>
                    <textarea type="text" autocomplete="off" class="form-control">
               @Model.Comentarios[contador]
                </textarea>
                }



                @if (contador == 15)
                {
            <div class="form-group" style="position:relative; left:80px; top:2px; width:500px;">
                <strong>Comentario Objetivo  2</strong>
                <textarea class="form-control" rows="7"> @Model.Comentarioobj2</textarea>
            </div>
                }



                @if (contador == 26)
                {
            <div class="form-group" style="position:relative; left:80px; top:2px; width:500px;">
                <strong>Comentario Objetivo  3</strong>
                <textarea class="form-control" rows="7"> @Model.Comentarioobj3</textarea>
            </div>
                }


                @if (contador == 32)
                {
                    <div class="form-group" style="position:relative; left:80px; top:2px; width:500px;">
                        <strong>Comentario Objetivo  4</strong>
                        <textarea class="form-control" rows="7"> @Model.Comentarioobj4</textarea>
                    </div>
                }


            </div>
        }

    </div>
    contador = contador + 1;
}
<br />
<br />
<br />
@*<div class="form-group">
        <strong>Comentario General</strong>
        <textarea class="form-control" rows="7"> @Model.formularioM[0].Comentario.Trim().ToString()</textarea>
    </div>*@